version: '3.8' 

services:
  postgres:
    image: postgres:alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"  
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mani
      # - POSTGRES_DB=postgres

  backend:
    image: mani1428/meduim_backend
    container_name: meduim_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://myuser:mani@postgres:5432/
      - JWT_SECRET="mysecretsupercode"

volumes:
  postgres_database:
